# Generated by Django 5.0.6 on 2024-07-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bid_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
