# Generated by Django 5.0.6 on 2024-07-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_vehicle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='file',
            field=models.FileField(blank=True, default='images/default-vehicle.png', upload_to='images/'),
        ),
    ]
