# Generated by Django 5.0.6 on 2024-07-20 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_bid_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='Bidding',
        ),
    ]
