# Generated by Django 5.0.6 on 2024-07-28 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_vehicle_views_vehicleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_no',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='v_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
