# Generated by Django 5.0.7 on 2024-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_alter_auctionhistory_auction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionhistory',
            old_name='sold',
            new_name='on_bid',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('on_auction', 'on_auction'), ('on_bid', 'on_bid')], default='available', max_length=10),
        ),
    ]
