# Generated by Django 5.0.6 on 2024-07-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image_profile_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
