# Generated by Django 5.0.7 on 2024-10-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_location_profile_location_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_number',
            new_name='ID_number',
        ),
    ]
