# Generated by Django 5.0.6 on 2024-07-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
