# Generated by Django 5.0.6 on 2024-07-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_created_by_remove_bid_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
