# Generated by Django 5.0.6 on 2024-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='file',
            field=models.FileField(blank=True, default='/images/toyota_ractis.jpg', upload_to='images/'),
        ),
    ]
