# Generated by Django 5.0.6 on 2024-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='file',
            field=models.FileField(blank=True, default='/toyota_ractis.jpg', upload_to='images/'),
        ),
    ]
