# Generated by Django 5.0.6 on 2024-07-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_rename_bid_bidding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.FileField(blank=True, default='images/default-vehicle.png', upload_to='vehicleimages/'),
        ),
    ]
