# Generated by Django 5.0.7 on 2024-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_auction_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bid_status',
            field=models.CharField(choices=[('available', 'available'), ('on_auction', 'on_auction'), ('sold', 'sold')], default='open', max_length=10),
        ),
    ]
