# Generated by Django 5.0.7 on 2024-07-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_alter_vehicle_bid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='bid_status',
            new_name='status',
        ),
    ]
