# Generated by Django 5.0.7 on 2024-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_rename_bid_status_vehicle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionhistory',
            options={'verbose_name_plural': ' Auction Histories'},
        ),
        migrations.AddField(
            model_name='auctionhistory',
            name='returned_to_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
