# Generated by Django 5.0.7 on 2024-07-31 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_auction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 9, 46, 0, 306328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
