# Generated by Django 5.0.7 on 2024-08-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0029_alter_auctionhistory_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('available', 'available'), ('on_auction', 'on_auction'), ('on_bid', 'on_bid')], default='available', max_length=10),
        ),
    ]
