# Generated by Django 5.0.7 on 2024-08-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0030_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('available', 'available'), ('on_auction', 'on_auction'), ('on_bid', 'on_bid')], default='idle', max_length=10),
        ),
    ]
