# Generated by Django 5.0.7 on 2024-11-10 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0036_financier_yard_vehicle_financier_vehicle_yard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Financier',
            field=models.ForeignKey(blank=True, default='MyCredit Ltd', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.financier'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='YOM',
            field=models.ForeignKey(default='2010', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.manufactureyear'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(default='Vehicle', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(default='SUV', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehicles.vehiclemodel'),
        ),
    ]
