# Generated by Django 5.0.7 on 2024-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0037_vehicle_approved_at_vehicle_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_hotsale',
            field=models.BooleanField(default=False),
        ),
    ]
