# Generated by Django 5.0.7 on 2024-11-11 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0037_vehicle_approved_at_vehicle_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
