# Generated by Django 5.0.7 on 2024-11-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0038_vehicle_is_hotsale'),
        ('vehicles', '0039_vehicle_is_hotsale'),
    ]

    operations = [
    ]
