# Generated by Django 5.0.7 on 2025-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0041_rename_created_at_bidding_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('available', 'available'), ('on_auction', 'on_auction'), ('on_bid', 'on_bid'), ('bid_won', 'bid_won'), ('sold', 'sold')], default='idle', max_length=10),
        ),
    ]
