# Generated by Django 5.0.7 on 2025-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0046_vehicle_disapproved_at_vehicle_disapproved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_dapproved',
            field=models.BooleanField(default=False),
        ),
    ]
