# Generated by Django 5.0.7 on 2025-01-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0047_vehicle_is_dapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_dapproved',
            new_name='is_disapproved',
        ),
    ]
