# Generated by Django 5.0.7 on 2025-01-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0050_awardhistory_awarded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclemake'),
        ),
    ]
