# Generated by Django 5.0.7 on 2025-02-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0051_vehiclemodel_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
