# Generated by Django 5.0.7 on 2025-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0052_bidding_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='referred_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
